from URDFParser import URDFParser
from FPGACodegen import FPGACodegen
from util import VerilogWriter, FileManager
from rbd_config import dim_list, urdf_file

#---------------------------------------------

parser = URDFParser()
robot = parser.parse(urdf_file)
fpga_codegen = FPGACodegen(robot)

#-------- urdf attrs needed for codegen-ing this file ----------------

num_links = robot.get_num_links_effective()
xform_bools_full = fpga_codegen.get_Xmat_sparsity_boolean_matrix_OR()
xform_bools = fpga_codegen.left_half_matrix(xform_bools_full)

#-------- File management -------------------

fm = FileManager("dqdfpijx_seq.v")
output_file_path = fm.get_output_file_path()
dqdfpijx_seq_file = open(output_file_path, "w")

vw = VerilogWriter(dqdfpijx_seq_file, dim_list, num_links)

#-------------------------------------------------------------------------------

# Make Stage 2&3 Transform Input Registers
def makeStage2n3XformInputRegs(dim_list,xform_bools):
   mat_str = ""
   mat_str = mat_str+"   reg signed[(WIDTH-1):0]"+"\n"
   xfm_str = ""
   xfm_str = vw.makeXformMatString("xform_in_",xform_bools,"               ","      ")
   mat_str = mat_str+xfm_str
   mat_str = mat_str+";"+"\n"
   return mat_str

# Make Stage 2&3 Transform Input Nonblocking Assignments
def makeStage2n3XformInputNonblockingAssignment(dim_list,xform_bools):
   mat_str = ""
   xfm_str = ""
   xfm_str = vw.makeXformMatNonblockingAssignmentString("xform_in_","xform_out_",xform_bools,"      ")
   mat_str = mat_str+xfm_str+"\n"
   return mat_str

#-------------------------------------------------------------------------------
dqdfpijx_seq_file.write("`timescale 1ns / 1ps"+"\n")
dqdfpijx_seq_file.write("\n")
dqdfpijx_seq_file.write("// dqd Forward Pass for Link i Input j"+"\n")
dqdfpijx_seq_file.write("\n")
dqdfpijx_seq_file.write("//------------------------------------------------------------------------------"+"\n")
dqdfpijx_seq_file.write("// dqdfpijx_seq Module"+"\n")
dqdfpijx_seq_file.write("//------------------------------------------------------------------------------"+"\n")
dqdfpijx_seq_file.write("module dqdfpijx_seq#(parameter WIDTH = 32,parameter DECIMAL_BITS = 16)("+"\n")
dqdfpijx_seq_file.write("   // clock"+"\n")
dqdfpijx_seq_file.write("   input  clk,"+"\n")
dqdfpijx_seq_file.write("   // stage booleans"+"\n")
dqdfpijx_seq_file.write("   input"+"\n")
dqdfpijx_seq_file.write("      s1_bool_in,s2_bool_in,s3_bool_in,"+"\n")
dqdfpijx_seq_file.write("   // link_in"+"\n")
dqdfpijx_seq_file.write("   input  ["+str(vw.get_bitwidth_array_def(num_links))+":0]"+"\n")
dqdfpijx_seq_file.write("      link_in,"+"\n")
dqdfpijx_seq_file.write("   // sin(q) and cos(q)"+"\n")
dqdfpijx_seq_file.write("   input  signed[(WIDTH-1):0]"+"\n")
dqdfpijx_seq_file.write("      sinq_val_in,cosq_val_in,"+"\n")
dqdfpijx_seq_file.write("   // qd_val_in"+"\n")
dqdfpijx_seq_file.write("   input  signed[(WIDTH-1):0]"+"\n")
dqdfpijx_seq_file.write("      qd_val_in,"+"\n")
dqdfpijx_seq_file.write("   // v_vec_in, 6 values"+"\n")
dqdfpijx_seq_file.write("   input  signed[(WIDTH-1):0]"+"\n")
dqdfpijx_seq_file.write("      v_vec_in_AX,v_vec_in_AY,v_vec_in_AZ,v_vec_in_LX,v_vec_in_LY,v_vec_in_LZ,"+"\n")
dqdfpijx_seq_file.write("   // mcross boolean"+"\n")
dqdfpijx_seq_file.write("   input  mcross,"+"\n")
dqdfpijx_seq_file.write("   // dv_vec_in, 6 values"+"\n")
dqdfpijx_seq_file.write("   input  signed[(WIDTH-1):0]"+"\n")
dqdfpijx_seq_file.write("      dv_vec_in_AX,dv_vec_in_AY,dv_vec_in_AZ,dv_vec_in_LX,dv_vec_in_LY,dv_vec_in_LZ,"+"\n")
dqdfpijx_seq_file.write("   // da_vec_in, 6 values"+"\n")
dqdfpijx_seq_file.write("   input  signed[(WIDTH-1):0]"+"\n")
dqdfpijx_seq_file.write("      da_vec_in_AX,da_vec_in_AY,da_vec_in_AZ,da_vec_in_LX,da_vec_in_LY,da_vec_in_LZ,"+"\n")
dqdfpijx_seq_file.write("   // dvdqd_vec_out, 6 values"+"\n")
dqdfpijx_seq_file.write("   output signed[(WIDTH-1):0]"+"\n")
dqdfpijx_seq_file.write("      dvdqd_vec_out_AX,dvdqd_vec_out_AY,dvdqd_vec_out_AZ,dvdqd_vec_out_LX,dvdqd_vec_out_LY,dvdqd_vec_out_LZ,"+"\n")
dqdfpijx_seq_file.write("   // dadqd_vec_out, 6 values"+"\n")
dqdfpijx_seq_file.write("   output signed[(WIDTH-1):0]"+"\n")
dqdfpijx_seq_file.write("      dadqd_vec_out_AX,dadqd_vec_out_AY,dadqd_vec_out_AZ,dadqd_vec_out_LX,dadqd_vec_out_LY,dadqd_vec_out_LZ,"+"\n")
dqdfpijx_seq_file.write("   // dfdqd_vec_out, 6 values"+"\n")
dqdfpijx_seq_file.write("   output signed[(WIDTH-1):0]"+"\n")
dqdfpijx_seq_file.write("      dfdqd_vec_out_AX,dfdqd_vec_out_AY,dfdqd_vec_out_AZ,dfdqd_vec_out_LX,dfdqd_vec_out_LY,dfdqd_vec_out_LZ"+"\n")
dqdfpijx_seq_file.write("   );"+"\n")
dqdfpijx_seq_file.write("\n")
dqdfpijx_seq_file.write("   //---------------------------------------------------------------------------"+"\n")
dqdfpijx_seq_file.write("   // internal wires and state"+"\n")
dqdfpijx_seq_file.write("   //---------------------------------------------------------------------------"+"\n")
dqdfpijx_seq_file.write("   // control inputs"+"\n")
dqdfpijx_seq_file.write("   wire"+"\n")
dqdfpijx_seq_file.write("      s1_bool,s2_bool,s3_bool;"+"\n")
dqdfpijx_seq_file.write("   // stage 1 inputs"+"\n")
dqdfpijx_seq_file.write("   wire signed[(WIDTH-1):0]"+"\n")
dqdfpijx_seq_file.write("      sinq_in,cosq_in;"+"\n")
dqdfpijx_seq_file.write("   wire signed[(WIDTH-1):0]"+"\n")
dqdfpijx_seq_file.write("      s1r1_in_AX,s1r1_in_AY,s1r1_in_AZ,s1r1_in_LX,s1r1_in_LY,s1r1_in_LZ,"+"\n")
dqdfpijx_seq_file.write("      s1r2_in_AX,s1r2_in_AY,s1r2_in_AZ,s1r2_in_LX,s1r2_in_LY,s1r2_in_LZ,"+"\n")
dqdfpijx_seq_file.write("      s1r3_in,"+"\n")
dqdfpijx_seq_file.write("      s1r4_in_AX,s1r4_in_AY,s1r4_in_AZ,s1r4_in_LX,s1r4_in_LY,s1r4_in_LZ;"+"\n")
#-------------------------------------------------------------------------------
dqdfpijx_seq_file.write("   // stage 2&3 xform inputs"+"\n")
mat_str = makeStage2n3XformInputRegs(dim_list,xform_bools)
dqdfpijx_seq_file.write(mat_str)
#-------------------------------------------------------------------------------
dqdfpijx_seq_file.write("   // stage 2 inputs"+"\n")
dqdfpijx_seq_file.write("   reg signed[(WIDTH-1):0]"+"\n")
dqdfpijx_seq_file.write("      s2r1_in_AX,s2r1_in_AY,s2r1_in_AZ,s2r1_in_LX,s2r1_in_LY,s2r1_in_LZ,"+"\n")
dqdfpijx_seq_file.write("      s2r2_in_AX,s2r2_in_AY,s2r2_in_AZ,s2r2_in_LX,s2r2_in_LY,s2r2_in_LZ,"+"\n")
dqdfpijx_seq_file.write("      s2r3_in_AX,s2r3_in_AY,s2r3_in_AZ,s2r3_in_LX,s2r3_in_LY,s2r3_in_LZ,"+"\n")
dqdfpijx_seq_file.write("      s2r4_in,"+"\n")
dqdfpijx_seq_file.write("      s2r5_in_AX,s2r5_in_AY,s2r5_in_AZ,s2r5_in_LX,s2r5_in_LY,s2r5_in_LZ;"+"\n")
dqdfpijx_seq_file.write("   // stage 3 inputs"+"\n")
dqdfpijx_seq_file.write("   reg signed[(WIDTH-1):0]"+"\n")
dqdfpijx_seq_file.write("      s3r1_in_AX,s3r1_in_AY,s3r1_in_AZ,s3r1_in_LX,s3r1_in_LY,s3r1_in_LZ,"+"\n")
dqdfpijx_seq_file.write("      s3r2_in_AX,s3r2_in_AY,s3r2_in_AZ,s3r2_in_LX,s3r2_in_LY,s3r2_in_LZ,"+"\n")
dqdfpijx_seq_file.write("      s3r3_in_AX,s3r3_in_AY,s3r3_in_AZ,s3r3_in_LX,s3r3_in_LY,s3r3_in_LZ,"+"\n")
dqdfpijx_seq_file.write("      s3r4_in_AX,s3r4_in_AY,s3r4_in_AZ,s3r4_in_LX,s3r4_in_LY,s3r4_in_LZ,"+"\n")
dqdfpijx_seq_file.write("      s3r5_in_AX,s3r5_in_AY,s3r5_in_AZ,s3r5_in_LX,s3r5_in_LY,s3r5_in_LZ;"+"\n")
dqdfpijx_seq_file.write("   // stage 1 outputs"+"\n")
dqdfpijx_seq_file.write("   wire signed[(WIDTH-1):0]"+"\n")
dqdfpijx_seq_file.write("      s1r1_out_AX,s1r1_out_AY,s1r1_out_AZ,s1r1_out_LX,s1r1_out_LY,s1r1_out_LZ,"+"\n")
dqdfpijx_seq_file.write("      s1r2_out_AX,s1r2_out_AY,s1r2_out_AZ,s1r2_out_LX,s1r2_out_LY,s1r2_out_LZ,"+"\n")
dqdfpijx_seq_file.write("      s1r3_out_AX,s1r3_out_AY,s1r3_out_AZ,s1r3_out_LX,s1r3_out_LY,s1r3_out_LZ,"+"\n")
dqdfpijx_seq_file.write("      s1r4_out,"+"\n")
dqdfpijx_seq_file.write("      s1r5_out_AX,s1r5_out_AY,s1r5_out_AZ,s1r5_out_LX,s1r5_out_LY,s1r5_out_LZ;"+"\n")
dqdfpijx_seq_file.write("   // stage 2 outputs"+"\n")
dqdfpijx_seq_file.write("   wire signed[(WIDTH-1):0]"+"\n")
dqdfpijx_seq_file.write("      s2r1_out_AX,s2r1_out_AY,s2r1_out_AZ,s2r1_out_LX,s2r1_out_LY,s2r1_out_LZ,"+"\n")
dqdfpijx_seq_file.write("      s2r2_out_AX,s2r2_out_AY,s2r2_out_AZ,s2r2_out_LX,s2r2_out_LY,s2r2_out_LZ,"+"\n")
dqdfpijx_seq_file.write("      s2r3_out_AX,s2r3_out_AY,s2r3_out_AZ,s2r3_out_LX,s2r3_out_LY,s2r3_out_LZ,"+"\n")
dqdfpijx_seq_file.write("      s2r4_out_AX,s2r4_out_AY,s2r4_out_AZ,s2r4_out_LX,s2r4_out_LY,s2r4_out_LZ,"+"\n")
dqdfpijx_seq_file.write("      s2r5_out_AX,s2r5_out_AY,s2r5_out_AZ,s2r5_out_LX,s2r5_out_LY,s2r5_out_LZ;"+"\n")
dqdfpijx_seq_file.write("   // stage 3 outputs"+"\n")
dqdfpijx_seq_file.write("   wire signed[(WIDTH-1):0]"+"\n")
dqdfpijx_seq_file.write("      s3r1_out_AX,s3r1_out_AY,s3r1_out_AZ,s3r1_out_LX,s3r1_out_LY,s3r1_out_LZ,"+"\n")
dqdfpijx_seq_file.write("      s3r2_out_AX,s3r2_out_AY,s3r2_out_AZ,s3r2_out_LX,s3r2_out_LY,s3r2_out_LZ,"+"\n")
dqdfpijx_seq_file.write("      s3r3_out_AX,s3r3_out_AY,s3r3_out_AZ,s3r3_out_LX,s3r3_out_LY,s3r3_out_LZ;"+"\n")
#-------------------------------------------------------------------------------
dqdfpijx_seq_file.write("   // xform outputs"+"\n")
mat_str = vw.makeXformOutputWires(xform_bools)
dqdfpijx_seq_file.write(mat_str)
#-------------------------------------------------------------------------------
dqdfpijx_seq_file.write("\n")
dqdfpijx_seq_file.write("   //---------------------------------------------------------------------------"+"\n")
dqdfpijx_seq_file.write("   // sequential"+"\n")
dqdfpijx_seq_file.write("   //---------------------------------------------------------------------------"+"\n")
dqdfpijx_seq_file.write("   always @ (posedge clk)"+"\n")
dqdfpijx_seq_file.write("   begin"+"\n")
#-------------------------------------------------------------------------------
dqdfpijx_seq_file.write("      // stage 2&3 xform inputs"+"\n")
mat_str = makeStage2n3XformInputNonblockingAssignment(dim_list,xform_bools)
dqdfpijx_seq_file.write(mat_str)
#-------------------------------------------------------------------------------
dqdfpijx_seq_file.write("      // stage 2 inputs"+"\n")
dqdfpijx_seq_file.write("      s2r1_in_AX <= s1r1_out_AX;"+"\n")
dqdfpijx_seq_file.write("      s2r1_in_AY <= s1r1_out_AY;"+"\n")
dqdfpijx_seq_file.write("      s2r1_in_AZ <= s1r1_out_AZ;"+"\n")
dqdfpijx_seq_file.write("      s2r1_in_LX <= s1r1_out_LX;"+"\n")
dqdfpijx_seq_file.write("      s2r1_in_LY <= s1r1_out_LY;"+"\n")
dqdfpijx_seq_file.write("      s2r1_in_LZ <= s1r1_out_LZ;"+"\n")
dqdfpijx_seq_file.write("      s2r2_in_AX <= s1r2_out_AX;"+"\n")
dqdfpijx_seq_file.write("      s2r2_in_AY <= s1r2_out_AY;"+"\n")
dqdfpijx_seq_file.write("      s2r2_in_AZ <= s1r2_out_AZ;"+"\n")
dqdfpijx_seq_file.write("      s2r2_in_LX <= s1r2_out_LX;"+"\n")
dqdfpijx_seq_file.write("      s2r2_in_LY <= s1r2_out_LY;"+"\n")
dqdfpijx_seq_file.write("      s2r2_in_LZ <= s1r2_out_LZ;"+"\n")
dqdfpijx_seq_file.write("      s2r3_in_AX <= s1r3_out_AX;"+"\n")
dqdfpijx_seq_file.write("      s2r3_in_AY <= s1r3_out_AY;"+"\n")
dqdfpijx_seq_file.write("      s2r3_in_AZ <= s1r3_out_AZ;"+"\n")
dqdfpijx_seq_file.write("      s2r3_in_LX <= s1r3_out_LX;"+"\n")
dqdfpijx_seq_file.write("      s2r3_in_LY <= s1r3_out_LY;"+"\n")
dqdfpijx_seq_file.write("      s2r3_in_LZ <= s1r3_out_LZ;"+"\n")
dqdfpijx_seq_file.write("      s2r4_in <= s1r4_out;"+"\n")
dqdfpijx_seq_file.write("      s2r5_in_AX <= s1r5_out_AX;"+"\n")
dqdfpijx_seq_file.write("      s2r5_in_AY <= s1r5_out_AY;"+"\n")
dqdfpijx_seq_file.write("      s2r5_in_AZ <= s1r5_out_AZ;"+"\n")
dqdfpijx_seq_file.write("      s2r5_in_LX <= s1r5_out_LX;"+"\n")
dqdfpijx_seq_file.write("      s2r5_in_LY <= s1r5_out_LY;"+"\n")
dqdfpijx_seq_file.write("      s2r5_in_LZ <= s1r5_out_LZ;"+"\n")
dqdfpijx_seq_file.write("      // stage 3 inputs"+"\n")
dqdfpijx_seq_file.write("      s3r1_in_AX <= s2r1_out_AX;"+"\n")
dqdfpijx_seq_file.write("      s3r1_in_AY <= s2r1_out_AY;"+"\n")
dqdfpijx_seq_file.write("      s3r1_in_AZ <= s2r1_out_AZ;"+"\n")
dqdfpijx_seq_file.write("      s3r1_in_LX <= s2r1_out_LX;"+"\n")
dqdfpijx_seq_file.write("      s3r1_in_LY <= s2r1_out_LY;"+"\n")
dqdfpijx_seq_file.write("      s3r1_in_LZ <= s2r1_out_LZ;"+"\n")
dqdfpijx_seq_file.write("      s3r2_in_AX <= s2r2_out_AX;"+"\n")
dqdfpijx_seq_file.write("      s3r2_in_AY <= s2r2_out_AY;"+"\n")
dqdfpijx_seq_file.write("      s3r2_in_AZ <= s2r2_out_AZ;"+"\n")
dqdfpijx_seq_file.write("      s3r2_in_LX <= s2r2_out_LX;"+"\n")
dqdfpijx_seq_file.write("      s3r2_in_LY <= s2r2_out_LY;"+"\n")
dqdfpijx_seq_file.write("      s3r2_in_LZ <= s2r2_out_LZ;"+"\n")
dqdfpijx_seq_file.write("      s3r3_in_AX <= s2r3_out_AX;"+"\n")
dqdfpijx_seq_file.write("      s3r3_in_AY <= s2r3_out_AY;"+"\n")
dqdfpijx_seq_file.write("      s3r3_in_AZ <= s2r3_out_AZ;"+"\n")
dqdfpijx_seq_file.write("      s3r3_in_LX <= s2r3_out_LX;"+"\n")
dqdfpijx_seq_file.write("      s3r3_in_LY <= s2r3_out_LY;"+"\n")
dqdfpijx_seq_file.write("      s3r3_in_LZ <= s2r3_out_LZ;"+"\n")
dqdfpijx_seq_file.write("      s3r4_in_AX <= s2r4_out_AX;"+"\n")
dqdfpijx_seq_file.write("      s3r4_in_AY <= s2r4_out_AY;"+"\n")
dqdfpijx_seq_file.write("      s3r4_in_AZ <= s2r4_out_AZ;"+"\n")
dqdfpijx_seq_file.write("      s3r4_in_LX <= s2r4_out_LX;"+"\n")
dqdfpijx_seq_file.write("      s3r4_in_LY <= s2r4_out_LY;"+"\n")
dqdfpijx_seq_file.write("      s3r4_in_LZ <= s2r4_out_LZ;"+"\n")
dqdfpijx_seq_file.write("      s3r5_in_AX <= s2r5_out_AX;"+"\n")
dqdfpijx_seq_file.write("      s3r5_in_AY <= s2r5_out_AY;"+"\n")
dqdfpijx_seq_file.write("      s3r5_in_AZ <= s2r5_out_AZ;"+"\n")
dqdfpijx_seq_file.write("      s3r5_in_LX <= s2r5_out_LX;"+"\n")
dqdfpijx_seq_file.write("      s3r5_in_LY <= s2r5_out_LY;"+"\n")
dqdfpijx_seq_file.write("      s3r5_in_LZ <= s2r5_out_LZ;"+"\n")
dqdfpijx_seq_file.write("   end"+"\n")
dqdfpijx_seq_file.write("\n")
dqdfpijx_seq_file.write("   //---------------------------------------------------------------------------"+"\n")
dqdfpijx_seq_file.write("   // combinational"+"\n")
dqdfpijx_seq_file.write("   //---------------------------------------------------------------------------"+"\n")
dqdfpijx_seq_file.write("   // control inputs"+"\n")
dqdfpijx_seq_file.write("   assign s1_bool = s1_bool_in;"+"\n")
dqdfpijx_seq_file.write("   assign s2_bool = s2_bool_in;"+"\n")
dqdfpijx_seq_file.write("   assign s3_bool = s3_bool_in;"+"\n")
dqdfpijx_seq_file.write("   // stage 1 inputs"+"\n")
dqdfpijx_seq_file.write("   assign sinq_in = sinq_val_in;"+"\n")
dqdfpijx_seq_file.write("   assign cosq_in = cosq_val_in;"+"\n")
dqdfpijx_seq_file.write("   assign s1r1_in_AX = v_vec_in_AX;"+"\n")
dqdfpijx_seq_file.write("   assign s1r1_in_AY = v_vec_in_AY;"+"\n")
dqdfpijx_seq_file.write("   assign s1r1_in_AZ = v_vec_in_AZ;"+"\n")
dqdfpijx_seq_file.write("   assign s1r1_in_LX = v_vec_in_LX;"+"\n")
dqdfpijx_seq_file.write("   assign s1r1_in_LY = v_vec_in_LY;"+"\n")
dqdfpijx_seq_file.write("   assign s1r1_in_LZ = v_vec_in_LZ;"+"\n")
dqdfpijx_seq_file.write("   assign s1r2_in_AX = da_vec_in_AX;"+"\n")
dqdfpijx_seq_file.write("   assign s1r2_in_AY = da_vec_in_AY;"+"\n")
dqdfpijx_seq_file.write("   assign s1r2_in_AZ = da_vec_in_AZ;"+"\n")
dqdfpijx_seq_file.write("   assign s1r2_in_LX = da_vec_in_LX;"+"\n")
dqdfpijx_seq_file.write("   assign s1r2_in_LY = da_vec_in_LY;"+"\n")
dqdfpijx_seq_file.write("   assign s1r2_in_LZ = da_vec_in_LZ;"+"\n")
dqdfpijx_seq_file.write("   assign s1r3_in = qd_val_in;"+"\n")
dqdfpijx_seq_file.write("   assign s1r4_in_AX = dv_vec_in_AX;"+"\n")
dqdfpijx_seq_file.write("   assign s1r4_in_AY = dv_vec_in_AY;"+"\n")
dqdfpijx_seq_file.write("   assign s1r4_in_AZ = dv_vec_in_AZ;"+"\n")
dqdfpijx_seq_file.write("   assign s1r4_in_LX = dv_vec_in_LX;"+"\n")
dqdfpijx_seq_file.write("   assign s1r4_in_LY = dv_vec_in_LY;"+"\n")
dqdfpijx_seq_file.write("   assign s1r4_in_LZ = dv_vec_in_LZ;"+"\n")
dqdfpijx_seq_file.write("\n")
dqdfpijx_seq_file.write("   dqdfpijxfold#(.WIDTH(WIDTH),.DECIMAL_BITS(DECIMAL_BITS))"+"\n")
dqdfpijx_seq_file.write("      dqdfpijxfolded("+"\n")
dqdfpijx_seq_file.write("      // link_in"+"\n")
dqdfpijx_seq_file.write("      .link_in(link_in),"+"\n")
dqdfpijx_seq_file.write("      // sin(q) and cos(q)"+"\n")
dqdfpijx_seq_file.write("      .sinq_in(sinq_in),.cosq_in(cosq_in),"+"\n")
#-------------------------------------------------------------------------------
dqdfpijx_seq_file.write("      // xform_in, 23 values"+"\n")
mat_str = vw.makeXformInputPortAssignment(xform_bools)
dqdfpijx_seq_file.write(mat_str)
#-------------------------------------------------------------------------------
dqdfpijx_seq_file.write("      // mcross boolean"+"\n")
dqdfpijx_seq_file.write("      .mcross(mcross),"+"\n")
dqdfpijx_seq_file.write("      // stage booleans"+"\n")
dqdfpijx_seq_file.write("      .s1_bool(s1_bool),.s2_bool(s2_bool),.s3_bool(s3_bool),"+"\n")
dqdfpijx_seq_file.write("      // stage 1 inputs"+"\n")
dqdfpijx_seq_file.write("      .s1r1_in_AX(s1r1_in_AX),.s1r1_in_AY(s1r1_in_AY),.s1r1_in_AZ(s1r1_in_AZ),.s1r1_in_LX(s1r1_in_LX),.s1r1_in_LY(s1r1_in_LY),.s1r1_in_LZ(s1r1_in_LZ),"+"\n")
dqdfpijx_seq_file.write("      .s1r2_in_AX(s1r2_in_AX),.s1r2_in_AY(s1r2_in_AY),.s1r2_in_AZ(s1r2_in_AZ),.s1r2_in_LX(s1r2_in_LX),.s1r2_in_LY(s1r2_in_LY),.s1r2_in_LZ(s1r2_in_LZ),"+"\n")
dqdfpijx_seq_file.write("      .s1r3_in(s1r3_in),"+"\n")
dqdfpijx_seq_file.write("      .s1r4_in_AX(s1r4_in_AX),.s1r4_in_AY(s1r4_in_AY),.s1r4_in_AZ(s1r4_in_AZ),.s1r4_in_LX(s1r4_in_LX),.s1r4_in_LY(s1r4_in_LY),.s1r4_in_LZ(s1r4_in_LZ),"+"\n")
dqdfpijx_seq_file.write("      // stage 2 inputs"+"\n")
dqdfpijx_seq_file.write("      .s2r1_in_AX(s2r1_in_AX),.s2r1_in_AY(s2r1_in_AY),.s2r1_in_AZ(s2r1_in_AZ),.s2r1_in_LX(s2r1_in_LX),.s2r1_in_LY(s2r1_in_LY),.s2r1_in_LZ(s2r1_in_LZ),"+"\n")
dqdfpijx_seq_file.write("      .s2r2_in_AX(s2r2_in_AX),.s2r2_in_AY(s2r2_in_AY),.s2r2_in_AZ(s2r2_in_AZ),.s2r2_in_LX(s2r2_in_LX),.s2r2_in_LY(s2r2_in_LY),.s2r2_in_LZ(s2r2_in_LZ),"+"\n")
dqdfpijx_seq_file.write("      .s2r3_in_AX(s2r3_in_AX),.s2r3_in_AY(s2r3_in_AY),.s2r3_in_AZ(s2r3_in_AZ),.s2r3_in_LX(s2r3_in_LX),.s2r3_in_LY(s2r3_in_LY),.s2r3_in_LZ(s2r3_in_LZ),"+"\n")
dqdfpijx_seq_file.write("      .s2r4_in(s2r4_in),"+"\n")
dqdfpijx_seq_file.write("      .s2r5_in_AX(s2r5_in_AX),.s2r5_in_AY(s2r5_in_AY),.s2r5_in_AZ(s2r5_in_AZ),.s2r5_in_LX(s2r5_in_LX),.s2r5_in_LY(s2r5_in_LY),.s2r5_in_LZ(s2r5_in_LZ),"+"\n")
dqdfpijx_seq_file.write("      // stage 3 inputs"+"\n")
dqdfpijx_seq_file.write("      .s3r1_in_AX(s3r1_in_AX),.s3r1_in_AY(s3r1_in_AY),.s3r1_in_AZ(s3r1_in_AZ),.s3r1_in_LX(s3r1_in_LX),.s3r1_in_LY(s3r1_in_LY),.s3r1_in_LZ(s3r1_in_LZ),"+"\n")
dqdfpijx_seq_file.write("      .s3r2_in_AX(s3r2_in_AX),.s3r2_in_AY(s3r2_in_AY),.s3r2_in_AZ(s3r2_in_AZ),.s3r2_in_LX(s3r2_in_LX),.s3r2_in_LY(s3r2_in_LY),.s3r2_in_LZ(s3r2_in_LZ),"+"\n")
dqdfpijx_seq_file.write("      .s3r3_in_AX(s3r3_in_AX),.s3r3_in_AY(s3r3_in_AY),.s3r3_in_AZ(s3r3_in_AZ),.s3r3_in_LX(s3r3_in_LX),.s3r3_in_LY(s3r3_in_LY),.s3r3_in_LZ(s3r3_in_LZ),"+"\n")
dqdfpijx_seq_file.write("      .s3r4_in_AX(s3r4_in_AX),.s3r4_in_AY(s3r4_in_AY),.s3r4_in_AZ(s3r4_in_AZ),.s3r4_in_LX(s3r4_in_LX),.s3r4_in_LY(s3r4_in_LY),.s3r4_in_LZ(s3r4_in_LZ),"+"\n")
dqdfpijx_seq_file.write("      .s3r5_in_AX(s3r5_in_AX),.s3r5_in_AY(s3r5_in_AY),.s3r5_in_AZ(s3r5_in_AZ),.s3r5_in_LX(s3r5_in_LX),.s3r5_in_LY(s3r5_in_LY),.s3r5_in_LZ(s3r5_in_LZ),"+"\n")
dqdfpijx_seq_file.write("      // stage 1 outputs"+"\n")
dqdfpijx_seq_file.write("      .s1r1_out_AX(s1r1_out_AX),.s1r1_out_AY(s1r1_out_AY),.s1r1_out_AZ(s1r1_out_AZ),.s1r1_out_LX(s1r1_out_LX),.s1r1_out_LY(s1r1_out_LY),.s1r1_out_LZ(s1r1_out_LZ),"+"\n")
dqdfpijx_seq_file.write("      .s1r2_out_AX(s1r2_out_AX),.s1r2_out_AY(s1r2_out_AY),.s1r2_out_AZ(s1r2_out_AZ),.s1r2_out_LX(s1r2_out_LX),.s1r2_out_LY(s1r2_out_LY),.s1r2_out_LZ(s1r2_out_LZ),"+"\n")
dqdfpijx_seq_file.write("      .s1r3_out_AX(s1r3_out_AX),.s1r3_out_AY(s1r3_out_AY),.s1r3_out_AZ(s1r3_out_AZ),.s1r3_out_LX(s1r3_out_LX),.s1r3_out_LY(s1r3_out_LY),.s1r3_out_LZ(s1r3_out_LZ),"+"\n")
dqdfpijx_seq_file.write("      .s1r4_out(s1r4_out),"+"\n")
dqdfpijx_seq_file.write("      .s1r5_out_AX(s1r5_out_AX),.s1r5_out_AY(s1r5_out_AY),.s1r5_out_AZ(s1r5_out_AZ),.s1r5_out_LX(s1r5_out_LX),.s1r5_out_LY(s1r5_out_LY),.s1r5_out_LZ(s1r5_out_LZ),"+"\n")
dqdfpijx_seq_file.write("      // stage 2 outputs"+"\n")
dqdfpijx_seq_file.write("      .s2r1_out_AX(s2r1_out_AX),.s2r1_out_AY(s2r1_out_AY),.s2r1_out_AZ(s2r1_out_AZ),.s2r1_out_LX(s2r1_out_LX),.s2r1_out_LY(s2r1_out_LY),.s2r1_out_LZ(s2r1_out_LZ),"+"\n")
dqdfpijx_seq_file.write("      .s2r2_out_AX(s2r2_out_AX),.s2r2_out_AY(s2r2_out_AY),.s2r2_out_AZ(s2r2_out_AZ),.s2r2_out_LX(s2r2_out_LX),.s2r2_out_LY(s2r2_out_LY),.s2r2_out_LZ(s2r2_out_LZ),"+"\n")
dqdfpijx_seq_file.write("      .s2r3_out_AX(s2r3_out_AX),.s2r3_out_AY(s2r3_out_AY),.s2r3_out_AZ(s2r3_out_AZ),.s2r3_out_LX(s2r3_out_LX),.s2r3_out_LY(s2r3_out_LY),.s2r3_out_LZ(s2r3_out_LZ),"+"\n")
dqdfpijx_seq_file.write("      .s2r4_out_AX(s2r4_out_AX),.s2r4_out_AY(s2r4_out_AY),.s2r4_out_AZ(s2r4_out_AZ),.s2r4_out_LX(s2r4_out_LX),.s2r4_out_LY(s2r4_out_LY),.s2r4_out_LZ(s2r4_out_LZ),"+"\n")
dqdfpijx_seq_file.write("      .s2r5_out_AX(s2r5_out_AX),.s2r5_out_AY(s2r5_out_AY),.s2r5_out_AZ(s2r5_out_AZ),.s2r5_out_LX(s2r5_out_LX),.s2r5_out_LY(s2r5_out_LY),.s2r5_out_LZ(s2r5_out_LZ),"+"\n")
dqdfpijx_seq_file.write("      // stage 3 outputs"+"\n")
dqdfpijx_seq_file.write("      .s3r1_out_AX(s3r1_out_AX),.s3r1_out_AY(s3r1_out_AY),.s3r1_out_AZ(s3r1_out_AZ),.s3r1_out_LX(s3r1_out_LX),.s3r1_out_LY(s3r1_out_LY),.s3r1_out_LZ(s3r1_out_LZ),"+"\n")
dqdfpijx_seq_file.write("      .s3r2_out_AX(s3r2_out_AX),.s3r2_out_AY(s3r2_out_AY),.s3r2_out_AZ(s3r2_out_AZ),.s3r2_out_LX(s3r2_out_LX),.s3r2_out_LY(s3r2_out_LY),.s3r2_out_LZ(s3r2_out_LZ),"+"\n")
dqdfpijx_seq_file.write("      .s3r3_out_AX(s3r3_out_AX),.s3r3_out_AY(s3r3_out_AY),.s3r3_out_AZ(s3r3_out_AZ),.s3r3_out_LX(s3r3_out_LX),.s3r3_out_LY(s3r3_out_LY),.s3r3_out_LZ(s3r3_out_LZ),"+"\n")
#-------------------------------------------------------------------------------
dqdfpijx_seq_file.write("      // xform_out"+"\n")
mat_str = vw.makeXformOutputPortAssignment(xform_bools)
dqdfpijx_seq_file.write(mat_str)
#-------------------------------------------------------------------------------
dqdfpijx_seq_file.write("      );"+"\n")
dqdfpijx_seq_file.write("\n")
dqdfpijx_seq_file.write("   //---------------------------------------------------------------------------"+"\n")
dqdfpijx_seq_file.write("   // outputs"+"\n")
dqdfpijx_seq_file.write("   //---------------------------------------------------------------------------"+"\n")
dqdfpijx_seq_file.write("   // dv/dqd"+"\n")
dqdfpijx_seq_file.write("   assign dvdqd_vec_out_AX = s3r3_out_AX;"+"\n")
dqdfpijx_seq_file.write("   assign dvdqd_vec_out_AY = s3r3_out_AY;"+"\n")
dqdfpijx_seq_file.write("   assign dvdqd_vec_out_AZ = s3r3_out_AZ;"+"\n")
dqdfpijx_seq_file.write("   assign dvdqd_vec_out_LX = s3r3_out_LX;"+"\n")
dqdfpijx_seq_file.write("   assign dvdqd_vec_out_LY = s3r3_out_LY;"+"\n")
dqdfpijx_seq_file.write("   assign dvdqd_vec_out_LZ = s3r3_out_LZ;"+"\n")
dqdfpijx_seq_file.write("   // da/dqd"+"\n")
dqdfpijx_seq_file.write("   assign dadqd_vec_out_AX = s3r2_out_AX;"+"\n")
dqdfpijx_seq_file.write("   assign dadqd_vec_out_AY = s3r2_out_AY;"+"\n")
dqdfpijx_seq_file.write("   assign dadqd_vec_out_AZ = s3r2_out_AZ;"+"\n")
dqdfpijx_seq_file.write("   assign dadqd_vec_out_LX = s3r2_out_LX;"+"\n")
dqdfpijx_seq_file.write("   assign dadqd_vec_out_LY = s3r2_out_LY;"+"\n")
dqdfpijx_seq_file.write("   assign dadqd_vec_out_LZ = s3r2_out_LZ;"+"\n")
dqdfpijx_seq_file.write("   // df/dqd"+"\n")
dqdfpijx_seq_file.write("   assign dfdqd_vec_out_AX = s3r1_out_AX;"+"\n")
dqdfpijx_seq_file.write("   assign dfdqd_vec_out_AY = s3r1_out_AY;"+"\n")
dqdfpijx_seq_file.write("   assign dfdqd_vec_out_AZ = s3r1_out_AZ;"+"\n")
dqdfpijx_seq_file.write("   assign dfdqd_vec_out_LX = s3r1_out_LX;"+"\n")
dqdfpijx_seq_file.write("   assign dfdqd_vec_out_LY = s3r1_out_LY;"+"\n")
dqdfpijx_seq_file.write("   assign dfdqd_vec_out_LZ = s3r1_out_LZ;"+"\n")
#-------------------------------------------------------------------------------
dqdfpijx_seq_file.write("\n")
#-------------------------------------------------------------------------------
dqdfpijx_seq_file.write("endmodule"+"\n")
#-------------------------------------------------------------------------------

# Close file
dqdfpijx_seq_file.close()
